import { z } from "zod";
export declare const EventTypeSchema: z.ZodEnum<["MONTHLY_REPORT_READY", "FEE_REMINDER_DUE", "ATTENDANCE_ALERT", "PERFORMANCE_ALERT", "CUSTOM_PARENT_NOTIFICATION"]>;
export type EventType = z.infer<typeof EventTypeSchema>;
export declare const JobStatusSchema: z.ZodEnum<["pending", "generating", "ready", "failed", "awaiting_manual_send", "completed"]>;
export type JobStatus = z.infer<typeof JobStatusSchema>;
export declare const CommunicationChannelSchema: z.ZodEnum<["whatsapp", "email", "sms"]>;
export type CommunicationChannel = z.infer<typeof CommunicationChannelSchema>;
export declare const AutomationJobSchema: z.ZodObject<{
    id: z.ZodString;
    eventType: z.ZodEnum<["MONTHLY_REPORT_READY", "FEE_REMINDER_DUE", "ATTENDANCE_ALERT", "PERFORMANCE_ALERT", "CUSTOM_PARENT_NOTIFICATION"]>;
    status: z.ZodEnum<["pending", "generating", "ready", "failed", "awaiting_manual_send", "completed"]>;
    payload: z.ZodRecord<z.ZodString, z.ZodUnknown>;
    createdBy: z.ZodOptional<z.ZodString>;
    createdAt: z.ZodDate;
    updatedAt: z.ZodDate;
    processedAt: z.ZodOptional<z.ZodDate>;
    failedAt: z.ZodOptional<z.ZodDate>;
    errorMessage: z.ZodOptional<z.ZodString>;
    retryCount: z.ZodNumber;
    metadata: z.ZodOptional<z.ZodRecord<z.ZodString, z.ZodUnknown>>;
}, "strip", z.ZodTypeAny, {
    id: string;
    createdAt: Date;
    status: "pending" | "completed" | "generating" | "ready" | "failed" | "awaiting_manual_send";
    updatedAt: Date;
    eventType: "MONTHLY_REPORT_READY" | "FEE_REMINDER_DUE" | "ATTENDANCE_ALERT" | "PERFORMANCE_ALERT" | "CUSTOM_PARENT_NOTIFICATION";
    payload: Record<string, unknown>;
    retryCount: number;
    metadata?: Record<string, unknown> | undefined;
    errorMessage?: string | undefined;
    createdBy?: string | undefined;
    processedAt?: Date | undefined;
    failedAt?: Date | undefined;
}, {
    id: string;
    createdAt: Date;
    status: "pending" | "completed" | "generating" | "ready" | "failed" | "awaiting_manual_send";
    updatedAt: Date;
    eventType: "MONTHLY_REPORT_READY" | "FEE_REMINDER_DUE" | "ATTENDANCE_ALERT" | "PERFORMANCE_ALERT" | "CUSTOM_PARENT_NOTIFICATION";
    payload: Record<string, unknown>;
    retryCount: number;
    metadata?: Record<string, unknown> | undefined;
    errorMessage?: string | undefined;
    createdBy?: string | undefined;
    processedAt?: Date | undefined;
    failedAt?: Date | undefined;
}>;
export type AutomationJob = z.infer<typeof AutomationJobSchema>;
export declare const CommunicationLogSchema: z.ZodObject<{
    id: z.ZodString;
    jobId: z.ZodString;
    studentId: z.ZodOptional<z.ZodString>;
    parentId: z.ZodOptional<z.ZodString>;
    channel: z.ZodEnum<["whatsapp", "email", "sms"]>;
    recipient: z.ZodString;
    message: z.ZodString;
    status: z.ZodEnum<["sent", "failed", "pending"]>;
    sentAt: z.ZodOptional<z.ZodDate>;
    failedAt: z.ZodOptional<z.ZodDate>;
    errorMessage: z.ZodOptional<z.ZodString>;
    metadata: z.ZodOptional<z.ZodRecord<z.ZodString, z.ZodUnknown>>;
    createdAt: z.ZodDate;
}, "strip", z.ZodTypeAny, {
    id: string;
    createdAt: Date;
    status: "pending" | "failed" | "sent";
    channel: "email" | "whatsapp" | "sms";
    message: string;
    recipient: string;
    jobId: string;
    metadata?: Record<string, unknown> | undefined;
    studentId?: string | undefined;
    parentId?: string | undefined;
    errorMessage?: string | undefined;
    sentAt?: Date | undefined;
    failedAt?: Date | undefined;
}, {
    id: string;
    createdAt: Date;
    status: "pending" | "failed" | "sent";
    channel: "email" | "whatsapp" | "sms";
    message: string;
    recipient: string;
    jobId: string;
    metadata?: Record<string, unknown> | undefined;
    studentId?: string | undefined;
    parentId?: string | undefined;
    errorMessage?: string | undefined;
    sentAt?: Date | undefined;
    failedAt?: Date | undefined;
}>;
export type CommunicationLog = z.infer<typeof CommunicationLogSchema>;
export declare const GeneratedReportSchema: z.ZodObject<{
    id: z.ZodString;
    jobId: z.ZodString;
    studentId: z.ZodOptional<z.ZodString>;
    reportType: z.ZodString;
    filePath: z.ZodString;
    fileName: z.ZodString;
    fileSize: z.ZodOptional<z.ZodNumber>;
    checksum: z.ZodOptional<z.ZodString>;
    metadata: z.ZodOptional<z.ZodRecord<z.ZodString, z.ZodUnknown>>;
    createdAt: z.ZodDate;
}, "strip", z.ZodTypeAny, {
    id: string;
    createdAt: Date;
    jobId: string;
    reportType: string;
    filePath: string;
    fileName: string;
    metadata?: Record<string, unknown> | undefined;
    studentId?: string | undefined;
    checksum?: string | undefined;
    fileSize?: number | undefined;
}, {
    id: string;
    createdAt: Date;
    jobId: string;
    reportType: string;
    filePath: string;
    fileName: string;
    metadata?: Record<string, unknown> | undefined;
    studentId?: string | undefined;
    checksum?: string | undefined;
    fileSize?: number | undefined;
}>;
export type GeneratedReport = z.infer<typeof GeneratedReportSchema>;
export declare const MessageDraftSchema: z.ZodObject<{
    id: z.ZodString;
    jobId: z.ZodString;
    studentId: z.ZodOptional<z.ZodString>;
    parentId: z.ZodOptional<z.ZodString>;
    channel: z.ZodEnum<["whatsapp", "email", "sms"]>;
    recipient: z.ZodString;
    subject: z.ZodOptional<z.ZodString>;
    message: z.ZodString;
    attachments: z.ZodOptional<z.ZodArray<z.ZodString, "many">>;
    status: z.ZodEnum<["draft", "reviewed", "sent"]>;
    reviewedBy: z.ZodOptional<z.ZodString>;
    reviewedAt: z.ZodOptional<z.ZodDate>;
    sentAt: z.ZodOptional<z.ZodDate>;
    metadata: z.ZodOptional<z.ZodRecord<z.ZodString, z.ZodUnknown>>;
    createdAt: z.ZodDate;
    updatedAt: z.ZodDate;
}, "strip", z.ZodTypeAny, {
    id: string;
    createdAt: Date;
    status: "draft" | "sent" | "reviewed";
    updatedAt: Date;
    channel: "email" | "whatsapp" | "sms";
    message: string;
    recipient: string;
    jobId: string;
    metadata?: Record<string, unknown> | undefined;
    studentId?: string | undefined;
    parentId?: string | undefined;
    subject?: string | undefined;
    reviewedBy?: string | undefined;
    reviewedAt?: Date | undefined;
    sentAt?: Date | undefined;
    attachments?: string[] | undefined;
}, {
    id: string;
    createdAt: Date;
    status: "draft" | "sent" | "reviewed";
    updatedAt: Date;
    channel: "email" | "whatsapp" | "sms";
    message: string;
    recipient: string;
    jobId: string;
    metadata?: Record<string, unknown> | undefined;
    studentId?: string | undefined;
    parentId?: string | undefined;
    subject?: string | undefined;
    reviewedBy?: string | undefined;
    reviewedAt?: Date | undefined;
    sentAt?: Date | undefined;
    attachments?: string[] | undefined;
}>;
export type MessageDraft = z.infer<typeof MessageDraftSchema>;
export declare const AutomationEventSchema: z.ZodObject<{
    id: z.ZodString;
    eventType: z.ZodEnum<["MONTHLY_REPORT_READY", "FEE_REMINDER_DUE", "ATTENDANCE_ALERT", "PERFORMANCE_ALERT", "CUSTOM_PARENT_NOTIFICATION"]>;
    entityType: z.ZodString;
    entityId: z.ZodString;
    payload: z.ZodRecord<z.ZodString, z.ZodUnknown>;
    triggeredAt: z.ZodDate;
    processed: z.ZodBoolean;
    processedAt: z.ZodOptional<z.ZodDate>;
    metadata: z.ZodOptional<z.ZodRecord<z.ZodString, z.ZodUnknown>>;
}, "strip", z.ZodTypeAny, {
    id: string;
    entityType: string;
    entityId: string;
    eventType: "MONTHLY_REPORT_READY" | "FEE_REMINDER_DUE" | "ATTENDANCE_ALERT" | "PERFORMANCE_ALERT" | "CUSTOM_PARENT_NOTIFICATION";
    payload: Record<string, unknown>;
    triggeredAt: Date;
    processed: boolean;
    metadata?: Record<string, unknown> | undefined;
    processedAt?: Date | undefined;
}, {
    id: string;
    entityType: string;
    entityId: string;
    eventType: "MONTHLY_REPORT_READY" | "FEE_REMINDER_DUE" | "ATTENDANCE_ALERT" | "PERFORMANCE_ALERT" | "CUSTOM_PARENT_NOTIFICATION";
    payload: Record<string, unknown>;
    triggeredAt: Date;
    processed: boolean;
    metadata?: Record<string, unknown> | undefined;
    processedAt?: Date | undefined;
}>;
export type AutomationEvent = z.infer<typeof AutomationEventSchema>;
export declare const PDFGenerationPayloadSchema: z.ZodObject<{
    studentId: z.ZodString;
    reportType: z.ZodString;
    data: z.ZodRecord<z.ZodString, z.ZodUnknown>;
    template: z.ZodString;
}, "strip", z.ZodTypeAny, {
    data: Record<string, unknown>;
    studentId: string;
    reportType: string;
    template: string;
}, {
    data: Record<string, unknown>;
    studentId: string;
    reportType: string;
    template: string;
}>;
export type PDFGenerationPayload = z.infer<typeof PDFGenerationPayloadSchema>;
export declare const WhatsAppDraftPayloadSchema: z.ZodObject<{
    recipient: z.ZodString;
    message: z.ZodString;
    attachments: z.ZodOptional<z.ZodArray<z.ZodString, "many">>;
}, "strip", z.ZodTypeAny, {
    message: string;
    recipient: string;
    attachments?: string[] | undefined;
}, {
    message: string;
    recipient: string;
    attachments?: string[] | undefined;
}>;
export type WhatsAppDraftPayload = z.infer<typeof WhatsAppDraftPayloadSchema>;
export declare const QueueItemSchema: z.ZodObject<{
    id: z.ZodString;
    jobId: z.ZodString;
    eventType: z.ZodEnum<["MONTHLY_REPORT_READY", "FEE_REMINDER_DUE", "ATTENDANCE_ALERT", "PERFORMANCE_ALERT", "CUSTOM_PARENT_NOTIFICATION"]>;
    payload: z.ZodRecord<z.ZodString, z.ZodUnknown>;
    status: z.ZodEnum<["pending", "generating", "ready", "failed", "awaiting_manual_send", "completed"]>;
    createdAt: z.ZodDate;
    updatedAt: z.ZodDate;
}, "strip", z.ZodTypeAny, {
    id: string;
    createdAt: Date;
    status: "pending" | "completed" | "generating" | "ready" | "failed" | "awaiting_manual_send";
    updatedAt: Date;
    eventType: "MONTHLY_REPORT_READY" | "FEE_REMINDER_DUE" | "ATTENDANCE_ALERT" | "PERFORMANCE_ALERT" | "CUSTOM_PARENT_NOTIFICATION";
    payload: Record<string, unknown>;
    jobId: string;
}, {
    id: string;
    createdAt: Date;
    status: "pending" | "completed" | "generating" | "ready" | "failed" | "awaiting_manual_send";
    updatedAt: Date;
    eventType: "MONTHLY_REPORT_READY" | "FEE_REMINDER_DUE" | "ATTENDANCE_ALERT" | "PERFORMANCE_ALERT" | "CUSTOM_PARENT_NOTIFICATION";
    payload: Record<string, unknown>;
    jobId: string;
}>;
export type QueueItem = z.infer<typeof QueueItemSchema>;
//# sourceMappingURL=index.d.ts.map