/**
 * Upcoming Fees Service
 * 
 * Generates upcoming/pending fee records on-the-fly from student data
 * (monthlyFeeAmount, feeCycleStartDate) rather than requiring manual creation.
 */
import { and, eq, gte, lt, sql } from "drizzle-orm";
import {
  db,
  feeRecordsTable,
  feeStatusTable,
  studentsTable,
} from "@toppers/db";

export interface UpcomingFee {
  studentId: string;
  studentName: string;
  studentCode: string;
  class: string;
  section: string;
  description: string;
  amountDue: number;
  amountPaid: number;
  dueDate: string;
  status: "pending" | "overdue" | "paid";
  isAutoGenerated: boolean;
}

/**
 * Returns upcoming/pending fees for all active students.
 * Combines already-created fee records with computed upcoming fees
 * derived from each student's monthlyFeeAmount and feeCycleStartDate.
 */
export async function getUpcomingFees(): Promise<UpcomingFee[]> {
  const result: UpcomingFee[] = [];

  // 1. Get all active students with their fee configuration
  const activeStudents = await db
    .select({
      id: studentsTable.id,
      studentCode: studentsTable.studentCode,
      fullName: studentsTable.fullName,
      class: studentsTable.class,
      section: studentsTable.section,
      monthlyFeeAmount: studentsTable.monthlyFeeAmount,
      feeCycleStartDate: studentsTable.feeCycleStartDate,
      nextFeeDueDate: studentsTable.nextFeeDueDate,
    })
    .from(studentsTable)
    .where(
      and(
        eq(studentsTable.status, "active"),
        eq(studentsTable.isArchived, false),
      ),
    );

  // 2. For each student, get their existing fee records
  for (const student of activeStudents) {
    // Fetch existing fee records for this student
    const existingRecords = await db
      .select({
        id: feeRecordsTable.id,
        description: feeRecordsTable.description,
        amountDue: feeRecordsTable.amountDue,
        amountPaid: feeRecordsTable.amountPaid,
        dueDate: feeRecordsTable.dueDate,
        status: feeRecordsTable.status,
      })
      .from(feeRecordsTable)
      .where(
        and(
          eq(feeRecordsTable.studentId, student.id),
          // Only pending or overdue — skip fully paid records
          sql`${feeRecordsTable.status} IN ('pending', 'overdue')`,
        ),
      );

    // Add existing pending/overdue records
    for (const record of existingRecords) {
      result.push({
        studentId: student.id,
        studentName: student.fullName,
        studentCode: student.studentCode,
        class: student.class,
        section: student.section,
        description: record.description,
        amountDue: record.amountDue,
        amountPaid: record.amountPaid,
        dueDate: record.dueDate,
        status: record.status as "pending" | "overdue" | "paid",
        isAutoGenerated: false,
      });
    }

    // 3. If no monthly fee configured, skip auto-generated entries
    if (!student.monthlyFeeAmount || student.monthlyFeeAmount <= 0) continue;

    // 4. Compute the next upcoming fee due date based on cycle
    const today = new Date();
    today.setHours(0, 0, 0, 0);

    let cycleStart: Date | null = null;
    if (student.feeCycleStartDate) {
      cycleStart = new Date(student.feeCycleStartDate);
    }

    // Calculate next due date:
    // If student has a feeCycleStartDate, compute the next fee cycle date.
    // Otherwise use the current month.
    let nextDueDate: Date;
    if (cycleStart && !isNaN(cycleStart.getTime())) {
      // Calculate months since cycle start
      const monthsSinceStart =
        (today.getFullYear() - cycleStart.getFullYear()) * 12 +
        (today.getMonth() - cycleStart.getMonth());
      const nextCycleMonths = Math.max(0, monthsSinceStart);
      nextDueDate = new Date(cycleStart);
      nextDueDate.setMonth(cycleStart.getMonth() + nextCycleMonths);

      // If this due date has already passed, advance to next month
      if (nextDueDate < today) {
        nextDueDate.setMonth(nextDueDate.getMonth() + 1);
      }
    } else {
      // No cycle start — default to end of current month
      nextDueDate = new Date(today.getFullYear(), today.getMonth() + 1, 0);
    }

    // Format date as YYYY-MM-DD
    const dueDateStr = nextDueDate.toISOString().split("T")[0];

    // 5. Check if an auto-generated record would be in the past (overdue)
    const isOverdue = nextDueDate < today;

    // 6. Check if there's already an existing record for this period
    const hasExistingForPeriod = existingRecords.some((r) => {
      // Match by month/year of due date
      const existingDue = new Date(r.dueDate);
      return (
        existingDue.getMonth() === nextDueDate.getMonth() &&
        existingDue.getFullYear() === nextDueDate.getFullYear()
      );
    });

    if (!hasExistingForPeriod) {
      result.push({
        studentId: student.id,
        studentName: student.fullName,
        studentCode: student.studentCode,
        class: student.class,
        section: student.section,
        description: `Monthly Fee - ${nextDueDate.toLocaleString("default", { month: "long", year: "numeric" })}`,
        amountDue: student.monthlyFeeAmount,
        amountPaid: 0,
        dueDate: dueDateStr,
        status: isOverdue ? "overdue" : "pending",
        isAutoGenerated: true,
      });
    }
  }

  // Sort by due date (closest first), then by student name
  result.sort((a, b) => {
    const dateCmp = a.dueDate.localeCompare(b.dueDate);
    if (dateCmp !== 0) return dateCmp;
    return a.studentName.localeCompare(b.studentName);
  });

  return result;
}